version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |

            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make tests
